### ISSUE TITLE
Typos causing errors in https://nix.dev/tutorials/working-with-local-files

### ISSUE THREAD

**Issue by biscotty666** [NixOS/nix.dev#1002]
Thank you for some very good docs/tutorials.

I just went through the above tutorial, and wanted to let you know of a couple of typos in the code which naturally cause errors.

1.  The command `nix-shell -p npins --run "npins init --bare; npins add github nixos nixpkgs --branch nixos-23.11"` creates a directory name `npins`. Later, in the sections on using `unions`, the `build.nix` file is (silently) altered to include the directory `./nix`. This should be `./npins` (and the addition to the file might be pointed out).

2. In the section on Matching files tracked by Git, the code block includes `git reset src/select.o result`. `select.o` should be `select.c`.

NixOS is often criticized, with some justification, for its documentation. This site is a counter-example, with top-class tutorials. Thank you again.

**Comment by fricklerhandwerk** [comment]
Thanks for catching these details!

> 2\. In the section on Matching files tracked by Git, the code block includes `git reset src/select.o result`. `select.o` should be `select.c`.

This is not correct. The command removes `select.o` from the staged files, which is what we want here.
