### ISSUE TITLE
Broken links to single-page Nix manuals

### ISSUE THREAD

**Issue by AlexMills0** [NixOS/nix.dev#1032]
The links shown in the screenshot do not work.

I will try to fix this (and submit a pull request) later, if nobody else beats me to it.

I am new to this and welcome all feedback.

![Screenshot_20240814_180145](https://github.com/user-attachments/assets/fd7d88fd-15d7-49a0-a694-3b1b0aaea302)

**Comment by fricklerhandwerk** [comment]
Hm, that should not happen. I'll check what's going on when I run the next version bump, soon-ish.

**Comment by fricklerhandwerk** [comment]
Aha, if you inspect what the links point to you'll notice that mutable version prefix is `latest` for all of them. Check the source:

https://github.com/NixOS/nix.dev/blob/master/source/reference/nix-manual.md?plain=1#L37-L45

Those instances need to be changed to the prefix corresponding to the actual version we want to point to. @AlexMills0 do you want to make a patch for that? Would be a great first contribution!
