### ISSUE TITLE
Issue on page /tutorials/cross-compilation.html

### ISSUE THREAD

**Issue by mayoff** [NixOS/nix.dev#1054]
This tutorial shows `nix repl '<nixpkgs>' -I nixpkgs=channel:nixos-23.11`. Later versions of `nix repl` require the `-f` flag, like this: `nix repl -f '<nixpkgs>' -I nixpkgs=channel:nixos-23.11`. It would be nice if the tutorial mentioned the change.

**Comment by xakep8** [comment]
I would like to work on this could you assign this issue to me?

**Comment by siddarth2810** [comment]
hii @mayoff , what do you think of something like this ? would love to hear your thoughts on this !

![screenshot-20241014-205047Z-selected](https://github.com/user-attachments/assets/39c8765d-f1d2-4cf0-8350-dcd395889c62)

**Comment by mayoff** [comment]
lgtm

**Comment by siddarth2810** [comment]
Great ! I raised a PR for your review. Thankss
