### ISSUE TITLE
Running into issues following the tutorial on the NixOS virtual machines

### ISSUE THREAD

**Issue by Azeirah** [NixOS/nix.dev#1071]
**Observations**
I'm following the instructions on the NixOS virtual machine tutorial, but running into a hard-to-understand error.

**Problem**
I am running NixOS. It is running from a flake, with the nixpkgs input set to nix-unstable.

I ran the following in a new clean directory:

```sh
$ nixos-generate-config --dir ./
$ nix-build '<nixpkgs/nixos>' -A vm -I nixpkgs=channel:nixos-24.05 -I nixos-config=./configuration.nix
{truncated}
$ ./result/bin/run-nixos-vm
Virtualisation disk image created.
/nix/store/xar911r1b3lmmg881b66qp2nvp6ksv27-qemu-host-cpu-only-8.2.6/bin/qemu-kvm: symbol lookup error: /nix/store/x1xy3qj2cllwrg33jyj7j28sf841cr1z-pipewire-1.2.3-jack/lib/libjack.so.0: undefined symbol: pw_log_topic_register
```

There's _something_ wrong with audio? I find it very difficult to debug this issue. Is it the host OS that is missing something? Is it the vm that is missing something? Is my host misconfigured for running VMs?

I also tried running it with further suggestions in the tutorial, but it doesn't work.

```
QEMU_KERNEL_PARAMS=console=ttyS0 ./result/bin/run-nixos-vm -nographic; reset
```

**Approaches**
Not sure. I just don't really get what's going on here

**Willing to help?**
Yep! I'm here to learn, and whatever I learn I will contribute back to the community

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix.dev/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by fricklerhandwerk** [comment]
This seems to be specific to your `configuration.nix`. Did you try removing the audio configuration just to check if it works then? If it does, then it could be about some wiring between QEMU and the guest OS.

**Comment by Azeirah** [comment]
Yeah I think this is an issue with my _host_'s qemu config, right?

My NixOS is set up for virtualization, and I have it working with a Windows vm with virtman.

```
$ rg virt
modules/windows-vm.nix
30:    virtualisation.spiceUSBRedirection.enable = true;

modules/virt.nix
6:  users.users.gcis.extraGroups = [ "libvirtd" ];
9:    virt-manager
10:    virt-viewer
14:    win-virtio
19:  virtualisation = {
20:    libvirtd = {

hosts/workstation/configuration.nix
26:  virtualisation.docker.enable = true;
301:      # Needed to run, via virtualenv + pip, matplotlib & tikzplotlib

modules/android-dev.nix
13:    users.users.lb.extraGroups = [ "adbusers" "kvm" "libvirtd" "adbusers" ];
14:    virtualisation.libvirtd.enable = true;
15:    programs.virt-manager.enable = true;
```

```
$ rg -C3 qemu
modules/virt.nix
19-  virtualisation = {
20-    libvirtd = {
21-      enable = true;
22:      qemu = {
23-        swtpm.enable = true;
24-        ovmf.enable = true;
25-        ovmf.packages = [ pkgs.OVMFFull.fd ];

modules/android-dev.nix
16-
17-    environment.systemPackages = with pkgs; [
18-      android-studio
19:      qemu
20-    ];
21-  };
22-}
```

```
$ rg jack
hosts/workstation/configuration.nix
88:      jack.enable = true;
```

Anything jumps out in this?

**Comment by Azeirah** [comment]
And if the host needs to be set-up correctly for running vms, would it make sense to add a link to a page explaining more about qemu/host os config? In particular one for NixOS would make a lot of sense I think

**Comment by fricklerhandwerk** [comment]
I think your host is fine. It's more that the guest wants audio, but QEMU parameters for the VM may not be correct (I suspect they don't allow the guest to have audio or don't wire it correctly, but that's just guessing).

**Comment by Azeirah** [comment]
Ah, I figured out the exact issue. My Nix config is still set-up with (very poor!) training wheels.

Someone on Reddit suggested to add a very, very large list of libraries to nix-ld so that many binaries run without compatibility issues. This is _not the Nix way_™.

If I prefix my qemu invocation with LD_LIBRARY_PATH="", it works.

```sh
LD_LIBRARY_PATH="" ./result/bin/run-nixos-vm -display gtk -audiodev none,id=snd0
```

I will definitely migrate away from using a globally configured nix-ld ASAP. This is exactly the kind of thing Nix is trying to avoid in the first place.

Time to lose those training wheels :)

Thanks for the suggestions @fricklerhandwerk 

Do you think there's something in this story that can help others?

**Comment by fricklerhandwerk** [comment]
> Do you think there's something in this story that can help others?

Yes, don't copy-paste and run code you don't fully understand.

That's the whole idea behind these tutorials. There should be nothing that feels magical, and every single thing should be there for a reason that can be explained in plain language.

**Comment by Azeirah** [comment]
> That's the whole idea behind these tutorials. There should be nothing that feels magical, and every single thing should be there for a reason that can be explained in plain language.

Sorry but that is very dismissive. I've been actively using Nix for half a year, and I'm figuring this out as part of a community. There are many people who are new to Nix like myself and I am doing my best to learn as well as I can, and share my knowledge as well as I can.

But there is a lot to learn.

How else do you learn other than trying, failing and standing up again?

**Comment by fricklerhandwerk** [comment]
Oh, please excuse that it came across that way, that was not my intention. I should have put more care into wording that.

I mean it compassionately from the painful experience that there's [no royal road to Nix](https://www.socratic-method.com/quote-meanings/euclid-there-is-no-royal-road-to-geometry). After many years of trying to solve problems on my own, and then more than two years of working on documentation, I can only conclude that doing things from the ground up is the only sustainable way -- as crazy as that may sound from the perspective of "but I just want things to work".

I don't want to write a novel about my philosophy of teaching, but roughly: in order to control your system you have to understand your system. And Nix is all about control. Also, cargo-culting just doesn't scale. There are no shortcuts. Nix exposes all the complexity of software, but it also gives you the full power of computation; in particular the power of building abstractions, which allows you to manage that complexity.

Abstractions the risk of being opaque or leaky though. Therefore I seriously recommend only working with code you actually understand. Adding stuff that's not yours will just add opportunities for errors to creep in, and it's really hard to debug things you're not intimately familiar with.

Starting from scratch is not as scary as it sounds, even if it's an up-front cost to doing what you're used to. Every migration comes at a cost. The cost is zero if you don't have any existing workflows, which is why much of Nix is still primarily suited for students and young people who don't have a lot of legacy that they need to port over or habits that need to change. I'd even argue that starting from scratch once in a while is quite healthy to re-assess whether the entire supply chain is sane, which often reveals that it's not, and in any case it's always an opportunity to further simplify things.

**Comment by Azeirah** [comment]
Thank you! I completely agree. Nix is a lot.

The biggest thing I learnt about Nix is that Nix isn't a "thing". Nix is a way of doing things, and it exists in different forms.

The Nix way of operating systems: NixOS

The Nix way of programming: NixLang

The Nix way of CI: Hydra (kinda)

The Nix way of package management: Nixpkgs

Decentralizing the Nix way: Flakes

I learnt the most about Nix by reading Eelco's original dissertation. It cleared up a lot of confusion for me. Nix is a way of doing dependency management with certainty. _how_ it does that is to a large extent "implementation details", and that is what you need to learn.

**Comment by Azeirah** [comment]
I'm also writing some of my findings by the way

https://www.reddit.com/r/NixOS/comments/1g8rmys/a_deterministic_walk_through_a_simple/

https://www.reddit.com/r/NixOS/comments/1fozy15/the_nixway_of_running_nonnixified_binaries_on_nix/

**Comment by fricklerhandwerk** [comment]
Wow, nice, thanks for sharing your insights!

In my humble opinion, it's absolutely enough to have these:

- store (derivations and isolated, cached process execution)
- language (a way to compose derivations)
- Nixpkgs (a software distribution built on top; a uniform interface to parameterize and compose builds)
- NixOS (a linux distribution built on top; a uniform interface to configure programs and applications)

The next step are distributed deployments (multi-node NixOS), and multiple groups are currently working on that. I think this is in many ways a natural extension of the Nix model, where state is unfolded in to a DAG of immutable content-addressed resources.

**Comment by Azeirah** [comment]
For what it's worth, I got the VM working now whahaha

I saw that the VM tutorial has been improved by a lot, that's good to see :)

What I think makes Nix different from all other distributions is that it makes an actual capital-S Science out of deployment (the problem of putting the desired bits to the desired location).

It's going to be a while before I understand this fully, but every hour I get some sort of a revelation this is at the level of "Oh my God, wait... does that mean I can do THAT with Nix?!"

It's a truly incredible philosophy, and I'm committed to keep learning :)
