### ISSUE TITLE
Dropdowns on page /tutorials/nixos/nixos-configuration-on-vm.html contain following text

### ISSUE THREAD

**Issue by dogoepp** [NixOS/nix.dev#1090]
There are two "detailed explanation" drop-downs on the page on virtual machine creation with Nix (https://nix.dev/tutorials/nixos/nixos-configuration-on-vm.html) which miss-behave. The first one contains most of the rest of the article, including the second drop-down which also contains more text than expected.

![image](https://github.com/user-attachments/assets/5a391460-d9d0-4854-ba16-ef1c7172581d)

I am unfortunately not familiar enough with the MyST syntax to locate the issue in the source.

**Comment by fricklerhandwerk** [comment]
Thanks for spotting! Fixed in https://github.com/NixOS/nix.dev/commit/e003610f3549dfc3ee2b11b253bd5140c1695690

**Comment by dogoepp** [comment]
Thanks @fricklerhandwerk for fixing :)
