### ISSUE TITLE
mkShell examples should use nativeBuildInputs  not buildInputs

### ISSUE THREAD

**Issue by arianvp** [NixOS/nix.dev#131]
buildInputs only works for legacy reasons as far as  I understand.

Furthermore benefit of `nativeBuildInputs` is that it makes  bash-completion work for things installed with nix-shell on `nixpkgs-unstable`

**Comment by eyeinsky** [comment]
@arianvp Could you expand why this is so? Recently while debugging an issue found this https://nixos.wiki/wiki/Development_environment_with_nix-shell#No_GSettings_schemas_are_installed_on_the_system where it uses `buildInputs`.

**Comment by arianvp** [comment]
You won't get autocomplete and man pages with buildInputs

**Comment by eyeinsky** [comment]
Other than that, will it "just work"? If I'm not mistaken using `buildInputs` will be often used by those who reuse their default.nix as shell.nix, and, khm, don't have the knowledge to know the difference.

**Comment by arianvp** [comment]
But for default.nix it's also wrong. Applications needed for your build need to go into nativeBuildInputs otherwise cross compilation does not work.  Libraries that are linked against go into buildInputs

**Comment by hsjobeki** [comment]
Fixed in nix.dev; we use packages, which is mapped to nativeBuildInputs:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/mkshell/default.nix#L41C3-L41C21
