### ISSUE TITLE
Remote building

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix.dev#157]
Existing tutotrials:

- https://nixos.org/manual/nix/unstable/advanced-topics/distributed-builds.html
- https://eipi.xyz/blog/nix-aarch64-remote/
- https://eipi.xyz/blog/building-on-remote-server-for-nixos-on-raspberry-pi/

Notes:

- builders-use-substitutes = true
- https://github.com/nix-dot-dev/nix.dev/pull/123#issuecomment-889786823

**Comment by Eisfunke** [comment]
I have a RPi3 onto which I deploy NixOS remotely using QEMU, I have some notes on that here: https://www.eisfunke.com/article/nixos-on-raspberry-pi.html#installing, might be helpful as well..

**Comment by fricklerhandwerk** [comment]
Troubleshooting tips: https://github.com/NixOS/nix/pull/5345

**Comment by fricklerhandwerk** [comment]
Duplicated in https://github.com/NixOS/nix.dev/issues/1013.
Closed by https://github.com/NixOS/nix.dev/pull/1045.
