### ISSUE TITLE
Don't show sidebar by default on small screens if javascript is disabled

### ISSUE THREAD

**Issue by TLATER** [NixOS/nix.dev#180]
Hi, I usually browse the web without JavaScript, unless it's *necessary* - saves bandwidth, makes pages load faster and conserves a bit of battery life, while tripping up most trackers not trivially defeated by ad block.

This normally works well for documentation sites, but not for nix.dev because the sidebar is expanded over the site content: 
![Screenshot_20210910-153814_Fennec](https://user-images.githubusercontent.com/6654841/132871143-47c806f0-5109-4cdd-a7e3-3a46eb39f98c.png)

In principle this is good, because it keeps the site navigatable on large screens, but it would be nice if this was expanded elsewhere (maybe top of the page) or not at all for small screens (i.e., anything with a screen width of less than the sidebar width + content width - this should be just about doable with CSS media things).

**Comment by willbush** [comment]
Believe has been fixed and can be closed. I just tested with Chrome / Vanadium on Android and Firefox on the Desktop (couldn't figure out how to block JS on Firefox for Android) and the side bar is now hidden by default.

Steps done:

1. *Using Google Chrome:*
   - Open Chrome.
   - Tap the three-dot menu icon in the top-right corner.
   - Go to "Settings."
   - Scroll down to "Site settings" and tap it.
   - Tap "JavaScript."
   - Toggle the switch to disable JavaScript.

2. *Using Firefox:*
   - Open Firefox.
   - Type =about:config= in the address bar and hit Enter.
   - Search for =javascript.enabled=.
   - Tap the toggle to change its value to =false=.

**Comment by fricklerhandwerk** [comment]
@willbush thanks for checking this!
