### ISSUE TITLE
Confused by `trustedBinaryCaches` in FAQ

### ISSUE THREAD

**Issue by austinbutler** [NixOS/nix.dev#272]
An undefined variable (`trustedBinaryCaches`) is used in the "How do I add a new binary cache?" section.

https://github.com/NixOS/nix.dev/blob/41faf1b5b4e4b706069359d5cdb8bf4ef036cf30/source/faq.md?plain=1#L16

What's the intent there? Should it be `trusted-substituters` instead? Even then, that's undefined in those blocks.

**Comment by willbush** [comment]
Looks like this issue can be closed as `trustedBinaryCaches` no longer occurs in the repo.

**Comment by austinbutler** [comment]
Looks like it was fixed by https://github.com/NixOS/nix.dev/pull/429.

**Comment by fricklerhandwerk** [comment]
Yes!
