### ISSUE TITLE
establish nomenclature

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix.dev#275]
we observe confusion around terminology, as newcomers find it hard to distinguish all the things that are called Nix.

proposal: https://github.com/NixOS/nix.dev/pull/263

Previous discussion: https://github.com/NixOS/nix/issues/835#issue-138660150

**Comment by olafklingt** [comment]
I agree with most of the initial proposal.
But nixpkgs is more than a Nix package collection.
Therefor I suggest to call the github:nixpkgs repository
**Nixpkgs**
and describe its as *biggest collection of Nix Packages and Nix Library and NixOS Modules*.

**Comment by fricklerhandwerk** [comment]
- @Ericson2314 we should rename the language, "Nix language" is a mouthful
    - @Mic92 "Nix expression language" even worse
        - renaming requires sweeping changes
            - @Ericson2314 that's what the documentation team is for, it should have permissions to do such at thing
    - @fricklerhandwerk concerned about social cost
        - even renaming starting from some release means we would have yet another resource inaccessible to discovery
        - will create a lot for friction for existing *and* new users
        - cost is prohibitive, ecosystem is so large that no one can pull off the concerted effort required to do this
        - should go incrementally, rather have verbose naming than breaking compatibility
        - @olaf agree, but `nixpkgs` is more than just the package collection: also library and module collection
            - @fricklerhandwerk the modules being in `nixpkgs` top level is a historical artifact
                - @olaf there is no progress on splitting them apart more clearly
                    - also the repository `nixpkgs` contains the package collection `nixpkgs`
                - @fricklerhandwerk next time go through proposal bit by bit to make a bundle for marketing and foundation to take or leave, document discarded alternatives

**Comment by uningan** [comment]
Normally when new language choose a common word as "lang" suffix:

golang (formerly, before be mainstream)
https://cuelang.org
https://www.rust-lang.org
https://dhall-lang.org


maybe `nixlang` have sense??

at least for separate domains nixos.org and nixlang.org


```
nix
nixos
nixpkgs
nixlang
```

**Comment by olafklingt** [comment]
@uningan what is nix in your list?
> ```
> nix
> nixos
> nixpkgs
> nixlang
> ```

**Comment by uningan** [comment]
nix, the tool only, but maybe have more sense `nixpm` as `npm` analogy.

Anyway is hard to me imagine `nix` tool as a package manager, officially it
is but i dont use it as package manager, but build system.


> From: olaf ***@***.***>
> Date: Fri, 12 Aug 2022 02:59:12 -0700
>
> @uningan what is nix in your list?
>> ```
>> nix
>> nixos
>> nixpkgs
>> nixlang
>> ```

-- 
Juanjo Presa
https://nadanix.com

**Comment by olafklingt** [comment]
Here is another try:

I add various terms because I believe we need nomenclature and categorization to clarify the use of the terms.

- Nix ecosystem 
    - Nix package manager [short: nix???]
        - Nix command line interface [short: Nix-cli]
        - Nix demon
    - Nix language [short: Nix-lang]
        - Nix expression
        - Nix file
        - Nix conventions
            - Module
            - Overlay
            - Flake
    -  Nix package repository [short: Nixpkgs]
        - Nix package collection
        - Nix library
        - NixOS module collection
- NixOS [long: Nix Operating System]

explanation:

*Nix package manager* is still a package manager in the same sense as (rust's) cargo, despite their scope is bigger than let say (debian's) apt.

*NixOS* is not part of the Nix ecosystem because it is build using the Nix ecosystem.

*Nix package manager*'s short name is unfortunately *nix* because alternatives would seem to imply that we have a command like nixpm etc. but we have nix-* (and nix *).

*Nix package collection* refers to the actual packages in the nixpkgs repository (and other repositories), 

*Nix package repository* refers to the repository nixpkgs that contains the package collection, library and modules

*NixOS module collection* are the Modules in the Nix package repository , because home-manger uses its own collection of modules for user configuration/services (which do not depend on NixOS).

**Comment by blaggacao** [comment]
> We stay on nixos.org and make extra effort to make clear that NixOS package manager works everywhere.

My senses tell me that people currently reject Nix, when it is recommended to them, because (among other things) when they see `nixos.org`, they see "OS" and feel invaded.

---

EDIT:

I feel the multiple semantic mismatches of _`github/nixpkgs`/ "Nix Package Repository"_ need to be resolved one way or the other.

In my opinion, each semantic dissonance matters disproportionally.

I don't want to jump into a proposal but rather raise this awareness to the Doc Team.

**Comment by fricklerhandwerk** [comment]
> I don't want to jump into a proposal but rather raise this awareness to the Doc Team.

@blaggacao Awareness exists, please check the team meeting notes. I ask you and everyone else, as a measure to keep signal-to-noise ratio high to indeed jump immediately to proposals or constructively discuss prior proposals so we can ideally converge on something solid.

The amount and dispersion of information to work through and keep track of is near-overwhelming as it is - it is the very reason for this team to exist and the goals we set for ourselves. I deliberately declared it a praxicracy: do the work and it will be taken seriously.

**Comment by blaggacao** [comment]
I've thought about this a little bit, and in order to resolve the repository misnomer, I suggest `NixOS/collections`, which contains (as in the above)

- The Nix Package Collection (`nixPC`)
- The Nix Library Collection (`nixLC`)
- The NixOS Modules Collection (`nixosMC`)

**Comment by fricklerhandwerk** [comment]
@olafklingt @blaggacao Thinking about this, being too specific at this point leads down infinite rabbit holes concerning repo organization that we simply cannot afford to deal with. This is an issue for the `nixpkgs` architecture team with @infinisil.

Proposal: Give the things names best-effort-style and calmly sweep under the rug for a while that there is a name collision between the GitHub repository `NixOS/nixpkgs` and what we call the Nix package collection.

Then let's continue discussion and refining proposals in the [respective PR](https://github.com/NixOS/nix.dev/pull/263), which allows structured suggestions and version control.

**Comment by fricklerhandwerk** [comment]
- @fricklerhandwerk Terminology: Establish firm way of naming things, it doesn't matter what it's named, just needs consistency. Whenever there's a discussion we can tell people to use this ([pull request](https://github.com/NixOS/nix.dev/pull/263/files))
    - @infinisil: Makes sense for common things we need to point out to people. Maybe a full writing standard document is overboard, as previously discussed
    - @fricklerhandwerk "Nix packages collection": kind of makes sense, but it's not really a word. Either "Nix package collection" or "Nix packages"
        - @edolstra: "Nixpkgs" is fine
            - @fricklerhandwerk: Don't know how to pronounce that by itself. Should have a proper name. Code name for SEO
            - @edolstra: "Nix packages" is what everybody uses, is fine
        - @fricklerhandwerk: "X is in Nix packages" is a bit unnatural. Saying "X is in the Nix package collection" would be better. "Nix packages" is plural, weird. "Nix package collection" is singular, makes more sense.
            - @jonringer: Language rules don't matter, there's so many exceptions
            - Luc: E.g. "United States"
            - @infinisil: I think it's fine, used by many people
            - @fricklerhandwerk: Used by many people is not a big argument. Not many people use Nix in general! Helping non-native speakers would be great by the term being easily pronouncable. "nixpkgs" can't easily be spoken aloud. Was "Nix packages" in the past, but should it continue to be?
        - @fricklerhandwerk: `nixpkgs` used for code, "Nix package collection" used for communication
            - @eelco: Causes confusion
            - @fricklerhandwerk: Can't (and don't have to) really pronounce code terms
            - @eelco: Not an issue people run into IMO. Stating that "Nixpkgs" should be pronounced "Nix packages" would be good.
            - @fricklerhandwerk: Easy to speak about, but writing is harder.
            - @jonringer: I tend to use "nixpkgs repository"
            - @domenkozar: Have a glossary to link to for the term nixpkgs
            - @fricklerhandwerk: Can't require people to link to glossary everywhere. Everybody does different things.
            - @infinisil: Glossary idea is good, we don't need to force other sites to use it
        - @jonringer: "Nix packages" non-ideal because there's also NUR and overlays, which are also Nix packages
        - @fricklerhandwerk: How about referring to the package collection as Nixpkgs, calling it "Nix packages" in speech, and call the repository `nixpkgs` in monospace?
            - [General agreement]
    - @fricklerhandwerk: "Nix package manager", doesn't capture the build system aspect, derivations, etc. "Package manager" is only deployment
        - @domenkozar: There's many components, no clear separation, nobody refers to the build system, there's the language, package manager and everything else, glued together
        - @fricklerhandwerk: @domenkozar suggested "Nix Core"
        - @eelco: Not a favor of renames, no clear benefit
            - @fricklerhandwerk: Less confusion, clear distinction. What is Nix? The Nix language, package manager, NixOS, etc.? When people are instructed in person, they get told about it in the beginning, it's fine. But for people not being instructed they get confused. We have to improve guides/tutorials. Should at least have a very distinct name
            - @eelco: How does renaming Nix package manager to "Nix core" help?
        - @infinisil: "Nix core" would that be the Nix repository?
            - @fricklerhandwerk: What Nix package manager meant before, the thing that builds packages, etc.
        - @eelco: "Nix Core" sounds like the Nix daemon or something
        - @jonringer: "Nix lang", "Nix" itself refers to more
        - @domenkozar: [back from connection issues] "Nix Core" solves confusion about "what is Nix". Nix Core becomes a collection tools in the Nix repository. "Nix Core" is intentionally ambiguous, doesn't refer to a specific component. SQL alchemy had the same problem, just core or more? Doing this change solves SEO, searching for "Nix Core" gives you what you mean. And clears up terminology. Nobody is fond of renames, but will resolve a lot of confusion. Doesn't have to be very involved, just rename repository.
        - @fricklerhandwerk: Nobody likes renames, but we need distinctive names to be clear for writing
        - @domenkozar: Ban "Nix", try having a culture where we're always clear with terms. "Nix" can become term for the whole ecosystem, not just the Nix repository parts.
        - @fricklerhandwerk: Is it okay to keep calling it "Nix package manager"? Tell people to add "package manager" for clarification.
        - @jonringer: Sounds good, should have docs on that. "Nix core" generally implies there's more than just core, like plugins, extensions, etc.
        - @fricklerhandwerk: Should have reliable mental models for what Nix is, and we have to introduce them in our material.
        - @jonringer: As long as it works it might be good enough. But maybe for docs would be better to have more well-defined terms
        - @fricklerhandwerk: Experts struggle to see confusion of beginners.
        - @infinisil: Both "Nix package manager" and "Nix core" aren't great.
        - @domenkozar: "Nix base" is an alternative. Needs an abstract term, but then it doesn't fit well because it's abstract.
        - @infinisil: "Nix CLI"?
            - @eelco: Wouldn't fit to the daemon
            - @jonringer: What about a future with Nickel, would Nix still represent the deamon?
        - @nrdxp: Used "Nix package compiler" in the past
        - @fricklerhandwerk: What makes Nix special is the derivation idea. Do we really want to significantly change names? Personally I don't really want to, but maybe we do: Renaming Nix language to something completely different, e.g. "sleet" (you know, dynamically typed mush), and the tool itself to something more oriented to the derivation concept making it unique, e.g. "drv". Maybe we don't want to go that far, but can we make it less crazy than now?
            - @eelco: I don't think it's crazy
            - @jonringer: Not intuitive, but not crazy. Learned Nix through Nix pills, and while it's good, it is a lot of content at once.
                - @nrdxp: Remembers that, more terrifying than helpful. Useful was digging into Nixpkgs. That was the idea for a Nix book, make it not intimidating. Maybe we need a brief functional programming tutorial, what is a pure function, etc.
- Luc: Procedural suggestion: Go into more concrete proposals during these meetings instead of discussing names one by one, more fruitful?
    - @fricklerhandwerk: We have those in the issues
- @fricklerhandwerk: Wanna go more into the terminology question?
    - @fricklerhandwerk: Seems to have not clear consensus, maybe not worth it for now
    - @olafklingt: [The PR](https://github.com/NixOS/nix.dev/pull/263) looks good. It seems we have to strike a balance between scope of changes and desired effect?
    - @domenkozar: Imagine onboarding thousands of developers, it's not too late to make it clearer, the longer we wait the harder it is.
    - @fricklerhandwerk: Agrees with @olaflkingt, should have some improvement without changing too much

**Comment by blaggacao** [comment]
Since this is being discussed, with a sharpened eye, I've gathered the following practical impression about the nomenclature. I don't have a particularly strong opinion, I just want to add this as a data point:

---

In [this post](https://discourse.nixos.org/t/restructuring-nixos-to-work-without-systemd-e-g-with-sysvinit/21298/5), it felt awkward to use Nix Packages instead of Nix Packages Collection.

There has to be a reason for it...


> The enormous business value that the Nix Package Collection provides.

vs.

> The enormus business value that Nix Packages provide.

I think the letter just requires a lot of contextual knowledge. Being a generalized plural, it's missing a definite article, blurring somewhat the actual reference:

It is the _collection_ of packages not the _plural_ of package that provides the business value, here.

Augmenting a mere plural into the meaning of a collection seems like that contextual tribal speech to me, that puts newcomers off.

But then, again, for the initiated, it has shifted meaning and consequentially numerus.

> The enormus business value that Nix Packages provide**s**.

How awkward, if you read it more than 3-5 times with the eyes and brain of an un-initiated.

**Comment by blaggacao** [comment]
I just had another cognizant encounter with this new nomenclature. (Data point)

---

> However, while they use the Nix Package Collection under the hood, they don't currently expose an interface into the Nix Language (as configuration language).

I felt the need to clarify with "as configuration language", and I think it was because the current confusion about "Nix" doesn't even make "Nix Language" sufficiently distinct in the minds of my target audience.

This legacy baggage might be hard to shave off and actually be an indication to come up with a more distuptive, but distinctive name, such as NixEL or any of the other suggestions made.

**Comment by fricklerhandwerk** [comment]
@blaggacao I also like NixEL (or Nixel) for being a distinct term that is pronounceable. But an actual rename is out of scope here, simply for being too big of a change to get it through in reasonable time. I'd support an RFC to rename Nix language if it's well-researched, summarizing and linking to all previous discussions, arguments, and proposals.

**Comment by asymmetric** [comment]
Is @eelco actually @edolstra?

**Comment by fricklerhandwerk** [comment]
- @fricklerhandwerk would like to find agreement to get something merged we can refer to in reviews
    - @domenkozar should move to the glossary
        - @fricklerhandwerk good idea
        - still has a few conflicts to resolve
            - @fricklerhandwerk will fix conflicts
        - @infinisil should link from glossary back to tutorials where one can learn about each concept
            - like an index in a book, showing page numbers of references to those terms
            - @fricklerhandwerk can Sphinx do this for us?
                - @domenkozar can try to find a plugin
            - a simple backlink to articles would be enough
            - this PR is already an improvement, this extra thing would be even nicer

**Comment by uningan** [comment]
Happy to see nix-lang.org registered by Determinate Systems

> From: David Arnold ***@***.***>
> Date: Fri, 12 Aug 2022 08:30:30 -0700
>
>> We stay on nixos.org and make extra effort to make clear that NixOS package manager works everywhere.
>
> My senses tell me that people currently reject Nix, when it is recommended to them, because (among other things) when they see `nixos.org`, they see "OS" and feel invaded.

-- 
Juanjo Presa
https://nadanix.com
