### ISSUE TITLE
clarify NixOS Wiki administration

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix.dev#279]
> @Mic92
> state of NixOS Wiki maintenance is unclear
- @fadenb is admin but not responsive at all
- Wiki runs on outdated version of mediawiki
- @Mic92 regularly pulls backups just to be sure
- A project of this size should have more people being able to actually do things

- Does anyone know how to get in touch with @fadenb to discuss a hand-over?
- Which other options do we have?

**Comment by fricklerhandwerk** [comment]
- @Mic92 the admin is active and appears to monitor the service, but is unresponsive
  - has a company in Munich, as last resort one could talk to him in person
      - could invite him to NixOS meetup in Munich
  - would be really nice to have a newer version of mediawiki
  - last known to have been in contact is @hexa
  - as a fallback we could set up a failover in the unfortunate case it is necessary
- @infinisil can we download the raw data and present it in a newer mediawiki?
  - @Mic92 yes
  - set up a read-only mirror on wiki.nixos.org and prepare everything for an emergency switch
- @domen ask him to come to the meetup and otherwise try to meet in person

**Comment by fricklerhandwerk** [comment]
- @fricklerhandwerk any updates?
    - @Mic92 no, @fadenb was not at the meetup
    - escalate to visiting him at the company?
        - @Mic92 maybe
    - would like to [make NixOS Wiki official](https://github.com/NixOS/nixos-homepage/pull/883), what would that entail?
        - @infinisil would require cooperation
            - ask more people to get in touch with him
                - @fricklerhandwerk not in support of this, it's rude
                    - any alternatives to perstering him or forking the Wiki?
                        - @Mic92 continuing as before and keeping a mirror
            - foundation should have some say in this
                - @Mic92 don't see the foundation agreeing on an official Wiki: @domenkozar and @edolstra would object
                    - historically they did not want to maintain it
                    - they closed down the old wiki and moved everything to the manual
                    - unofficial (current) wiki was set up on GitHub, later moved to mediawiki
                    - these days, maintaining it on the infra side should not be an issue, we have the nixos and community infra

**Comment by Mic92** [comment]
I had another life sign of the wiki admin this week.

```
fadenb: Webserver was just unexpectedly restarted... Admin team is investigating
fadenb: Escalated to hoster as there is no indication on the VM that anything went wrong 🤷‍♂️ Everything is back up and seems to be working
```

So at least they try to keep it running. Also they don't like communicating too much.

**Comment by fricklerhandwerk** [comment]
Closing as we decided a long time ago that the wiki is not in @NixOS/documentation-team's domain of responsibility.
