### ISSUE TITLE
teaching Nix 3 CLI and Flakes

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix.dev#281]

**Comment by domenkozar** [comment]
![2023-07-17-120427_830x571_escrotum](https://github.com/NixOS/nix.dev/assets/126339/27ab855f-3da6-48eb-b4dd-d673a140de31)
![2023-07-17-120337_917x440_escrotum](https://github.com/NixOS/nix.dev/assets/126339/7d917e94-9c4d-4271-8277-b31e2975300f)

**Comment by Ericson2314** [comment]
I left a comment on the tweet: https://twitter.com/ericson2314_/status/1680630061353824256 We should not promote unstable features, or "unstable" doesn't mean anything. Period. I wrote an RFC for how and when to stabilize Flakes, https://github.com/NixOS/rfcs/pull/136. Pro-Flakes people have largely ignored the RFC.

If any wants Flakes to be promoted in official teaching material, they should want Flakes to be stable, and they should therefore engage with the RFC or counter-propose something else.
