### ISSUE TITLE
Do you know about `Teaching Tech Together` book?

### ISSUE THREAD

**Issue by bew** [NixOS/nix.dev#292]
_(Since discussions are not enabled on this repo, here is an issue, move it appropriately if needed)_

I recently came across this incredible resource on how to build a tech course that sticks:

Teaching Tech Together
http://teachtogether.tech/en/ (online version)

It talks about a lot of interesting topics around teaching & learning, like:
- how we learn, what happens, how 
- the value of concept map & mental models
- how to design a lesson, what's important, how to present it bit by bit, ...
- how to design exercises / examples
- building a "community of practice" (not just people that learn & forget)
- and a lot of other things...

As you're all putting lots of thoughts on Nix documentation at large, I was wondering if you knew this book, which could be of great guidance in structuring the various tutorials, the book, and other teaching/learning resources, ...

Have a good day/night/... :)

**Comment by fricklerhandwerk** [comment]
@bew thanks a lot, this does indeed look very valuable. I'm basing my work on [How Learning Works](https://www.wiley.com/en-us/How+Learning+Works%3A+Seven+Research+Based+Principles+for+Smart+Teaching-p-9780470484104) (2010), which seems to have a lot of overlap, but Teaching Tech Together is pleasantly focused on tech.

**Comment by fricklerhandwerk** [comment]
After talking to @ners I am convinced that the Haskell and Nix have very similar issues with onboarding and learning. Here is a [Haskell book that I was made aware of today, which has an exemplary outline or roadmap](https://haskellbook.com/progress/), and a notable background story of two co-authors, one of which comes from tech and the other from the humanities.

In #265 I propose a similar outline for what nix.dev should eventually become: The Nix Book.

I would go even further now: **Let us build an authoritative Nix curriculum that instructors and autodidacts can orient around.** It should be driven by the tenets behind [Software Carpentry](https://software-carpentry.org/lessons/), which I would summarize from ([Software Carpentry - Lessons Learned](https://www.youtube.com/watch?v=1e26rp6qPbA)) as "teaching is hard, let's not waste effort, and instead get together to curate an evidence-based single source of truth on each subject".

Related: #310
