### ISSUE TITLE
Issue on page /tutorials/installing-nixos-on-a-raspberry-pi.html

### ISSUE THREAD

**Issue by olavfosse** [NixOS/nix.dev#309]
The instructions do not work. It displays some systemd logs and then crashes. I have tried updating the firmware.

**Comment by domenkozar** [comment]
Could you share logs?

**Comment by olavfosse** [comment]
I don't have logs. I forgot to say, but I was using a newer image from Hydra 😅. Specifically https://hydra.nixos.org/build/187548854. Following the instructions with the exact image in the instructions worked 🥳🥳🥳.

I'll add a note warning that installing with newer images might break.

**Comment by willbush** [comment]
OP made commit to their fork, but never made a PR I think. However, I doubt adding that note is needed anymore since no one else has had the same issue in 2 years since this was opened.

**Comment by fricklerhandwerk** [comment]
The tutorial was updated in 2023, which should have made it work. (Documentation rendered from VM tests when?)
