### ISSUE TITLE
Accommodate divnix/nix-book

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix.dev#310]
@jonringer and @nrdxp work on their vision of a [Nix Book](https://github.com/divnix/nix-book) ([Discourse announcement](https://discourse.nixos.org/t/help-on-creating-a-nix-book/21126)).

Let us see how we can align goals, coordinate efforts, and avoid redundant work.

**Comment by jonringer** [comment]
It's still quite a WIP, but the first few chapters I think are in a decent rough-draft state

**Comment by nrdxp** [comment]
Perhaps all that's needed is to eventually host the book at book.nix.dev, and have a link to it on the side panel. I think have a distinct book, seperate from a collection of tutorials and reference material is highly useful, and was a huge success for Rust.

One of the things the Rust book does really well is to go over this foreign new concept "the borrow checker" in a way that is repeatedly addressed through a repetition of examples. In our case, the new foreign concept is "the derivation", and I think a similarly structured approach would pay of dividends.

**Comment by fricklerhandwerk** [comment]
Yes, what I would like to clarify in general, and missed to ask today, is if we should more clearly separate the Nix Book as tutorial from nix.dev as guides. Because the [Nix language tutorial](https://github.com/NixOS/nix.dev/pull/267) is definitely a tutorial, and the beginner guides for CLI use and all that stuff are also kind of tutorials, but maybe also guides, because they help solve concrete problems.

Should we restructure nix.dev and sort out tutorials into the Nix Book to be really clear about this?

**Comment by jonringer** [comment]
@fricklerhandwerk Wow, your note taking is excellent

**Comment by fricklerhandwerk** [comment]
@jonringer today credit goes to @infinisil - thanks again!

**Comment by blaggacao** [comment]
I may add to this point:

> Every time we hire someone, it's hard for them to get onboarded.

The real problem, in my opinion is that package management is a side effect of "Nix as config language with superpowers", as described in `std`'s "Why Nix?".

So from that angle, a layered explanation that doesn't _start_ with package management, but _arrives_ at package management through fundamental properties of the Nix Language would go a long way in clarifying things and serve the DevOps use case a ton.

**Comment by domenkozar** [comment]
> Perhaps all that's needed is to eventually host the book at book.nix.dev, and have a link to it on the side panel. I think have a distinct book, seperate from a collection of tutorials and reference material is highly useful, and was a huge success for Rust.
> 
> One of the things the Rust book does really well is to go over this foreign new concept "the borrow checker" in a way that is repeatedly addressed through a repetition of examples throughout the material. In our case, the new foreign concept is "the derivation", and I think a similarly structured approach would pay dividends.

My idea has always been to make a book out of nix.dev content, so those two aren't orthogonal.

Having it as a free resource first and a book later optimizes for access to free education.

:100: there should be a book, if we make that a community effort we'll be much faster once we get the initial handshaking done

**Comment by fricklerhandwerk** [comment]
- @fricklerhandwerk unfortunately @jonringer and @nrdxp are not here today
- @fricklerhandwerk would like to clarify objectives: tutorials vs. guides
    - see diataxis.fr
    - problem so far has been, with all material, that it is not really focused, therefore not meeting user needs well
        - for nix.dev we have multiple new PRs which are either guide or tutorial
        - @domenkozar right now nix.dev is just a top-level collection
            - we could have a curated curriculum and next to it a bunch of useful stuff
            - structure will emerge once we have more material
            - @fricklerhandwerk it's about presentation, we should clearly separate the two types
                - also like the idea to have curated core and collection of things
                    - we can offer people reviews if they want to contribute stuff
                        - editing the wiki will usually not be replied to
                    - additional collection can even be just pull requests

**Comment by blaggacao** [comment]
> problem so far has been, with all material, that it is not really focused, therefore not meeting user needs well

In my opinion, it's suboptimale to distribute these four aspects across different projects, but if path-dependency commands us to (temporarily) do so, I would cut it in half rather on the "for work" / "for study" axis.

These are the primary learning situations that a user is actually _in_ at any given moment.

**Comment by fricklerhandwerk** [comment]
@Jonringer looks like you didn't have time to continue working on it. Closing for now. Please get in touch if you get to it again and you'd like to collaborate. :)
