### ISSUE TITLE
cloudflare denial of service

### ISSUE THREAD

**Issue by urandom2** [NixOS/nix.dev#319]
as discussed on the forum[0], cloudflare makes this service hard to use. can we either turn down the bot protection or migrate to fastly, the provider for all other official nix sites? this is a read only service so thn risk of malicious activity seems low.

0] https://discourse.nixos.org/t/21255

**Comment by domenkozar** [comment]
under attack mode is off, do you still experience this?

**Comment by urandom2** [comment]
I no longer have to solve captchas, but I still get the interstitial page and have to wait for it to "secure my connection"

**Comment by willbush** [comment]
Seems like this issue can be closed now?

**Comment by fricklerhandwerk** [comment]
Yes, we're on Netlify now, for better or worse.
