### ISSUE TITLE
Keep pull requests open for comments after they have been merged

### ISSUE THREAD

**Issue by SuperSandro2000** [NixOS/nix.dev#321]
For example in #261 there was a comment which directly addressed me and now I can't reply to it anymore because the PR got merged.

**Comment by domenkozar** [comment]
Any ideas how to allow this? For master protected branch I only require status to pass and a pull request.

**Comment by SuperSandro2000** [comment]
The problem is that the github-action locked the PR conversation which is not really great to do.

**Comment by domenkozar** [comment]
I understand what's happening, but I don't know to to stop it.
