### ISSUE TITLE
Getting the URL of the system channel as a regular user?

### ISSUE THREAD

**Issue by michalrus** [NixOS/nix.dev#323]
How to do this? I could run:

```
$ sudo nix-channel --list
```

And add this command to sudoers.

Or set appropriate permissions for `/root` (701) and `/root/.nix-channels` (644), and read that file directly.

But both these solutions seem hacky. =)

**Comment by willbush** [comment]
Can this be closed. I looked in `nix` repo and it seems there have been bugs in the past where things would work differently depending on if ran without sudo, with sudo, or as su. Doesn't seem like anything actionable can be done here.

**Comment by michalrus** [comment]
Okay then 👍
