### ISSUE TITLE
Publish rendered HTML for each Pull Request

### ISSUE THREAD

**Issue by zupo** [NixOS/nix.dev#348]
As a maintainer of nix.dev documentation, I want to be able to quickly merge trivial PRs. 

Current process:
1. I look at the changes, they look fine.
2. I open up my terminal, `git pull` latest `nix.dev` repo.
3. Wait a while for the env to build.
4. Read (for the N-th time) how to generate docs locally.
5. Generate docs.
6. Look at the generated HTML to verify the changes are good.

Ideal process:
1. I look at the changes, they look fine.
2. I click a link in the PR which takes me to a page with generated HTML
3. Verify changes are good.

**Comment by fricklerhandwerk** [comment]
It already exists, but only for non-fork branches.

**Comment by zupo** [comment]
I'm assuming there are reasons to not build non-fork branches. What are they? 

The upside of building non-fork branches too is to save me a bunch of time when reviewing PRs such as https://github.com/NixOS/nix.dev/pull/347 and https://github.com/NixOS/nix.dev/pull/343.

**Comment by zupo** [comment]
The current process for reviewing non-fork branches is even worse, actually:

1. I look at the changes, they look fine.
2. I open up my terminal, `git pull` latest `nix.dev` repo.
3. Google how to pull a remote fork. I never seem to be able to remember this. 
4. Wait a (longer) while for the env to build.
5. Read (for the N-th time) how to generate docs locally.
6. Generate docs.
7. Look at the generated HTML to verify the changes are good.

I.e. I just won't do it. And potentially merge a breaking change.

**Comment by zupo** [comment]
An alternative to building all fork branches by default is only building them when someone with merge access submits a comment like `/cloudflare rebuild docs` or sth.

**Comment by zupo** [comment]
This is not as trivial as it sounds. 

Problem 1: Cloudflare Pages app does not have OOTB support for building branches in forks. We need to use the https://github.com/tomjschuster/cloudflare-pages-deploy-action GitHub Action to achive building pages for branches in forks. This requires some work, but should be doable.

Problem 2: https://github.com/tomjschuster/cloudflare-pages-deploy-action requires the use of Cloudflare API Token. This token is account-wide and cannot be restricted to a single project. Currently, nix.dev project is owned by @domenkozar's personal Cloudflare account, along with his other projects. So it's impossible for us to get the Cloudflare API Token.

Solution: 
1. Get the NixOS Foundation to open an account on Cloudflare. 
2. Migrate nix.dev project to the new Foundation's account.
3. Generate the suitable Cloudflare API Token and configure https://github.com/tomjschuster/cloudflare-pages-deploy-action.

@lucperkins: could you please work with the foundation to get the Cloudflare account opened? I can then do the rest.

**Comment by domenkozar** [comment]
https://github.com/cloudflare/pages-action allows us to do that securely.

**Comment by zupo** [comment]
I'll take a look.

**Comment by domenkozar** [comment]
Like this: https://github.com/hsjobeki/noogle/blob/main/.github/workflows/main.yml

**Comment by yukiisbored** [comment]
I wonder if it's worth looking into other static site host options. I know that nixos.org uses Netlify. Maybe we should consider moving to Netlify if it allows deploy previews on PRs from forks?

**Comment by yukiisbored** [comment]
@fricklerhandwerk Could I request to be assigned to this issue? Thanks
