### ISSUE TITLE
Add information on contributing documentation in "How to Contribute"

### ISSUE THREAD

**Issue by yukiisbored** [NixOS/nix.dev#350]
The ["How to contribute"](https://nix.dev/tutorials/contributing) page currently only contains information on contributing code to Nixpkgs, NixOS, and Nix. 

Similary, there should be a section dedicated to contributing documentation for each component.

**Comment by yukiisbored** [comment]
Related PR: https://github.com/NixOS/nix.dev/pull/371

**Comment by lucperkins** [comment]
Resolved by #371
