### ISSUE TITLE
Establish single glossary 

### ISSUE THREAD

**Issue by yukiisbored** [NixOS/nix.dev#377]
Currently there are two glossaries on https://github.com/NixOS/nix.dev/blob/master/CONTRIBUTING.md#terminology and https://nix.dev/glossary

They should be unified into https://nix.dev/glossary.

**Comment by davidak** [comment]
The goal of https://github.com/NixOS/nix.dev/issues/275 was to have authoritative terminology, which was provided. But this mixes it with existing terminology which i think did not get the same review. For example, i think the definition for reproducible is impossible and probably wrong (https://github.com/NixOS/nix.dev/issues/464).

So this issue should be fixed to have an usable authoritative terminology.

cc @fricklerhandwerk

**Comment by fricklerhandwerk** [comment]
@davidak Agreed, it needs more work. Please open a specific issue we can address.
