### ISSUE TITLE
[advice] Add install method to <https://nix.dev/tutorials/install-nix#linux>

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nix.dev#398]
In archlinux, we can `sudo pacman -S nix` to install nix. Why not add this information to <https://nix.dev/tutorials/install-nix#linux>?

**Comment by Freed-Wu** [comment]
See <https://wiki.archlinux.org/title/Nix>

**Comment by fricklerhandwerk** [comment]
In principle: sure. Feel free to make a PR with additional instructions [here](https://github.com/NixOS/nix.dev/blob/master/source/tutorials/install-nix.md?plain=1). It should note though that this is method not supported by Nix maintainers. 

For that reason I'm neither opposed nor enthusiastic to the idea, and would ask for and expect input from more people. 

Also that [Usage](https://wiki.archlinux.org/title/Nix#Usage) section needs an update. [`nix-env` is frowned upon](https://github.com/NixOS/nix.dev/issues/17) for many reasons, and there are better ways to start out with Nix. Could you replace it with a link to nix.dev?
