### ISSUE TITLE
Endorse license for use for Nix documentation

### ISSUE THREAD

**Issue by Gabriella439** [NixOS/nix.dev#465]
Would it be worth the Nix documentation team endorsing a specific license for people to use when authoring Nix documentation?  The idea here is that some authors might not have strong opinions on the choice of license and giving them some guidance can help unify licenses so that it's easier to port and adapt existing documentation.

In the absence of such an endorsement they might unintentionally pick a license that makes it harder to adapt their work.  We can still ask them to release the work under a new copyright and they'd probably happily oblige if we asked, but it might streamline things if they pick the preferred license the first time.

Edit by @fricklerhandwerk: [implementation hints](https://github.com/NixOS/nix.dev/issues/465#issuecomment-1507611912)

**Comment by yukiisbored** [comment]
Just gonna list common options and who uses them:

- [GNU Free Documentation License]: Wikipedia ([dual licensed with CC-BY-SA 3.0](https://en.wikipedia.org/wiki/Wikipedia:Licensing_update)), ArchWiki (GFDL 1.3 or later)
- [Creative Commons] (I guess which one is open to debate): Kubernetes ([CC-BY 4.0](https://github.com/kubernetes/website/blob/main/LICENSE)), GitLab ([CC-BY-SA 4.0](https://gitlab.com/gitlab-org/gitlab/-/blob/master/LICENSE#L5))
- Same license as main project: Rust ([Apache 2.0/MIT](https://github.com/rust-lang/book/blob/main/CONTRIBUTING.md#licensing))

[GNU Free Documentation License]: https://www.gnu.org/licenses/fdl-1.3.en.html
[Creative Commons]: https://creativecommons.org/licenses/
