### ISSUE TITLE
documentation team: project board structure and function

### ISSUE THREAD

**Issue by olafklingt** [NixOS/nix.dev#470]
what should the nix documentation project board structure and function be like?

**Comment by asymmetric** [comment]
I would prefer to use labels for categorizing issues, and columns for status.

But that leads to the problem that the issues in the board come from different repos (nix.dev, nix, nixpkgs), so if we're going to use labels, we'll need to be able to admin them on all 3 -- which could be a challenge, I imagine?

**Comment by fricklerhandwerk** [comment]
Closing since we're working with the board as it is for some time now.
