### ISSUE TITLE
Task: How to find the right people to get help?

### ISSUE THREAD

**Issue by infinisil** [NixOS/nix.dev#496]
- What: A section to describe how to find the right people to get help.
    - Not relevant is how to find the right documentation, this is about people with knowledge specifically
- Where to put the result:
  - A section in https://nix.dev/contributing/
- Who: @asymmetric
- Outline: From most specific to least specific
  - be clear about expectations:
      - the less specific you get, the less likely is to get a reply
  - check for who may be knowledgeable on the particular thing you're working on:
     - the commit log for the relevant files
     - `CODEOWNERS`
     - community teams responsible for that domain
         - https://nixos.org/community/#governance-teams
         - https://github.com/NixOS/nixpkgs/blob/master/maintainers/team-list.nix
  - ask around on the relevant communication channels
    - Look at the NixOS Matrix space for all the rooms, include link
    - Check specific Discourse categories
  - ask the general user base:
     - Matrix https://app.element.io/#/room/#nix:nixos.org
     - Discourse
- estimated effort: 2 hours
    - write it down nicely (1h)
    - process reviews (1h)
- Related:
  - https://nixos.org/community/
- Person to contact for help and review: @infinisil

**Comment by yukiisbored** [comment]
I believe some clarification is needed that this issue means unblock as in "I'm stuck with this problem" and not "I'm blocked from contributing to a GitHub organization".

**Comment by asymmetric** [comment]
Maybe we should just change to "...to get help"
