### ISSUE TITLE
Unable to reach out to organization administrator regarding my application for Google Season of Docs

### ISSUE THREAD

**Issue by jaskiratsingh2000** [NixOS/nix.dev#503]
Hi @fricklerhandwerk I have been trying to reach out to you but unable to know how eaxctly I should reach out to you for expressing my interest in the Google Season of Docs program under Nix. Can you please share your email adresss with me so that I can share all my information along with statement of iinterest and experince. can you pklease let me know?
Looking forward to hearing from you!

Thanks!

**Comment by fricklerhandwerk** [comment]
Hi @jaskiratsingh2000, please check my GitHub profile, it states my email address. Apparently the link to the docs team details was broken, fixed it now.
