### ISSUE TITLE
Move from poetry to nixpkgs

### ISSUE THREAD

**Issue by yukiisbored** [NixOS/nix.dev#505]
I think poetry adds unnecessary complexity to the project and a learning curve to contributors who may not be familiar with it (especially considering that we plan to teach Nix/nixpkgs here, not poetry).

In addition, I believe it's not necessary as nix.dev isn't distributed as a Python package/project and the only thing that's needed to build the project is a shell environment with sphinx and additional libraries we use.

From what I see, one of the potential reasons why poetry is used is because it allows using dependabot but I don't think that's important for this project as we don't really need the latest software and the latest version of nixpkgs is sufficient for our needs.

In addition, doing this allow nix.dev to be used as an example by interested readers who wants to contribute to the project.

A couple things need to be done:
- [ ] Verify every piece of dependency is on nixpkgs
  - If one isn't available, decide whether to submit a new package to nixpkgs or find an alternative that's already in nixpkgs.
- [ ] Move from poetry to nixpkgs

**Comment by zmitchell** [comment]
Under `python310Packages` we have:

- [x] livereload
- [x] myst-parser
- [x] sphinx
- [x] sphinx-book-theme
- [x] sphinx-copybutton
- [x] sphinx-design
- [x] black

I haven't checked that these all play well together or render properly (the `pyproject.toml` requires Python 3.7), but the dependencies are at least there.

**Comment by zmitchell** [comment]
If we're getting rid of `poetry` would we just have a single `mkDerivation` that's essentially what `nix-dev-html` does?

**Comment by zmitchell** [comment]
I've removed all of the `poetry` stuff but I've hit this error:
```
error: Package ‘python3.10-sphinx-book-theme-0.3.3’ in /nix/store/0acd255ca1v8m4xcg5wjhi9pgmx7q2s5-source/pkgs/development/python-modules/sphinx-book-theme/default.nix:35 is marked as broken, refusing to evaluate.
```

**Comment by zmitchell** [comment]
Looks like there's a [compatibility issue](https://github.com/executablebooks/sphinx-book-theme/issues/592) between this theme and `sphinx`. The version of `sphinx` in `python310Packages` is v5.1.1, but v0.3.3 of `sphinx-book-theme` isn't compatible with this version of `sphinx`. Luckily there's a later version of `sphinx-book-theme`, v1.0.1, that _is_ compatible, I'm just not sure how to use it because I'm a Nix noob. Is this where I would use an overlay of some sort?

**Comment by fricklerhandwerk** [comment]
Please put up the change as a PR, then people can help you out on the concrete code.

**Comment by zmitchell** [comment]
The PR is here: https://github.com/NixOS/nix.dev/pull/515

**Comment by willbush** [comment]
PR was merged. This can be closed.
