### ISSUE TITLE
Proposal to make GitHub templates to aid in those contributing. 

### ISSUE THREAD

**Issue by JeremiahSecrist** [NixOS/nix.dev#510]
# Problem Statement 
When making an attempt to contribute, it can be difficult to ascertain the quality of the work submitted. Especially When trying to educate individuals on a given subject.

# Solution Proposal
When creating an issue, templates can be made to guide the kind of problem you are wanting to solve. In addition, These issues can link the user to recommended prerequisite readings to aid in building a solid foundation.

## Example scenario
Say a user would like to add information to the repo regarding flakes. They would like to illustrate how a user can use flakes to build a reproducible shell. Have they considered what type of info they would like to submit?
Given this scenario, a checklist may look like:

---

Sources:
- [ ] Please list out the sources you used to validate the methods used.
- [ ] What version of nix is this information valid with

Type of content:
- [ ] Vocabulary
- [ ] Process (Guide, Tutorial, etc.)
- [ ] Conceptual

Conflicts:
- [ ] Check for existing information that your content may conflict with.
- [ ] Does this new information require consolidation of other guides / topics?

Principles:
Which of the following principles does your work best fit within?  
- [ ] Considers reader's prior knowledge and addresses it.
- [ ] Aids in revealing the quality and depth of the readers' organization of the knowledge
- [ ] Seeks to motivate and direct the reader
- [ ] Gives the individual an obtainable goal with measurable results.
- [ ] Empowers the user to be self-directed with future lessons

---

### Addendum 
Please keep in mind, the following is just an example of an issue / pr template that a user could submit. The exact amount and types that we use should have thought put into them and common aspects of those types considered when creating. 

### Additional Readings:
[Github Templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)

**Comment by arouzing** [comment]
It seems that PR #501 Relates to this topic.
