### ISSUE TITLE
Update Nix Documentation Team page on nixos.org

### ISSUE THREAD

**Issue by zmitchell** [NixOS/nix.dev#514]
The [team page](https://nixos.org/community/teams/documentation.html) only lists @infinisil and @fricklerhandwerk as the team members, but there are now at least a few regular contributors that should also be on the list.

**Comment by fricklerhandwerk** [comment]
Yeah, sigh, this is double book keeping we have to live with until someone finds time to rewrite the web site enough for us to stop caring. 😐

**Comment by infinisil** [comment]
This is now being kept up-to-date since https://github.com/NixOS/nixos-homepage/pull/1136 :)
