### ISSUE TITLE
<nixpkgs>: say what's the recommended approach

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix.dev#53]

**Comment by fiadliel** [comment]
If you're going to recommend trying not to depend on `<nixpkgs>` for hermetic builds, I did notice that nix-shell still depends on it to find bash (https://github.com/NixOS/nixpkgs/issues/27493). Should `NIX_BUILD_SHELL` also be set for those cases?

(pre-commits started to fail after setting `skip_adding_nixpkgs_channel` in install-nix-action).

**Comment by willbush** [comment]
Current docs have a "Towards reproducibility" feel. I get the impression this has solved itself and can be closed.

**Comment by fricklerhandwerk** [comment]
Yeah, I think we're being quite clear about lookup paths now.
