### ISSUE TITLE
nix registry not mentioned in pinning reference

### ISSUE THREAD

**Issue by bburdette** [NixOS/nix.dev#558]
**Observations**
Went to look at the pinning reference, but `nix registry` is not mentioned there.  That seems like a significant omission from a discussion on pinning.  

**Problem**
Is `nix registry` an antipattern?  Is it not relevant to the discussion somehow?  I'm curious as to why it's not there.    

**Approaches**
Would like it to be mentioned, even if only to dismiss it.

**Comment by fricklerhandwerk** [comment]
[`nix registry` is an experimental feature], and one of the more controversial ones from the [flakes proposal](https://github.com/NixOS/rfcs/pull/49). The documentation team focuses on stable features, for various reasons, mostly centered around limited resources for maintenance.

We should eventually provide a clear answer along these lines, and I'd be happy to review and merge a PR in that direction.

Until then we're working on illuminating the flakes situation here:

- https://github.com/NixOS/nix.dev/pull/545
- https://github.com/NixOS/nix.dev/pull/546
- https://github.com/NixOS/nix.dev/pull/547
