### ISSUE TITLE
Learning Journey tutorial: `PATH` and `PATH`-like variables

### ISSUE THREAD

**Issue by infinisil** [NixOS/nix.dev#571]
If you're interested in working on this task, reply in this issue to make sure the work isn't duplicated!

### What
- Explain the `PATH` convention on Unix, binaries are looked up there
- `nix-shell` can change `PATH`
- `which` or `command -v` to look up binaries
- How installed Nix packages become available on `PATH`, default Nix `PATH` entry
- Link to `makeWrapper`, which can wrap packages with a different `PATH`
- Mention `shellHook`
- You can change `PATH` with setup hooks
- There's various other `PATH`-like variables for different languages, like `PYTHONPATH`, maybe `NIX_PATH`?, java class path?, mention `LD_LIBRARY_PATH`

### How
- Where to put the result: A new file in https://github.com/NixOS/nix.dev/tree/master/source/tutorials
- Person to contact for help:
  - Technical: @infinisil
  - Editorial: @zmitchell

**Comment by fricklerhandwerk** [comment]
That sounds like concepts to me, but covering that is valuable regardless.

**Comment by zmitchell** [comment]
My opinion is that we should have something in Concepts about the various ways in which `PATH`-like environment variables are managed for you, but in this tutorial series we should also touch on it since this need for managing variables like `PYTHONPATH` motivates the need to use things like `python.withPackages`, which is a common user need.

**Comment by yukiisbored** [comment]
Hey, I'm up to the task of writing this!

**Comment by roberth** [comment]
> That sounds like concepts/explanation to me, but covering that is valuable regardless.

Indeed the description is covers (too) many things.

I think there's a tutorial hiding in there though. How about: "Bundling command dependencies into a package"? - a `makeWrapper` tutorial.

That touches on most of the items, although I wouldn't bring `nix-shell` into this. It doesn't handle just `PATH`, so you'd have a lot of explaining to do if you don't want to lie.

**Comment by fricklerhandwerk** [comment]
Agree with @roberth. Also there is some reference basis in the Nixpkgs manual to work on top off, and also potential to improve that while at it.

**Comment by yukiisbored** [comment]
I think at the very least there should be a concept page for PATH and other search paths (i.e. `LD_LIBRARY_PATH`) since the Nix ecosystem (ab)use them a lot and AFAIK, there's no good single reference documentation which explains them all.

**Comment by yukiisbored** [comment]
Not sure how a `makeWrapper` tutorial is something urgently needed since I feel most people will interact with programming language-specific builders for Python, Node, etc.

**Comment by zmitchell** [comment]
Should we close this? It sounds like we've decided that this isn't actually a tutorial.

**Comment by fricklerhandwerk** [comment]
We could move it to Nixpkgs and aim for improving the reference docs on stdenv.
