### ISSUE TITLE
Make nix.dev official

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix.dev#578]
## Project description

nix.dev is now the official documentation resource. A few things need to be done so that's indeed clear to beginners.

## Steps

- https://github.com/NixOS/nix.dev/issues/536
- https://github.com/NixOS/nix.dev/issues/535
- https://github.com/NixOS/nix.dev/issues/481

**Comment by zmitchell** [comment]
Discussed in documentation team meeting, seems done barring DNS issues
