### ISSUE TITLE
Raspberry Pi 4: nixos-hardware config doesn't work with 23.05

### ISSUE THREAD

**Issue by Eisfunke** [NixOS/nix.dev#590]
**Observations**

With NixOS 23.05 on a RPi 4 the overlays from the nixos-hardware repo seem to fail to build. See this issue: https://github.com/NixOS/nixos-hardware/issues/631
I can confirm these problems from own experience.

**Problem**
being broken is bad

**Approaches**
See this comment: https://github.com/NixOS/nixos-hardware/issues/631#issuecomment-1584100732

It seems with newer kernels the settings from nixos-hardware aren't needed anymore, you just need some specific kernel modules in the initrd.

I can confirm that 23.05 runs and boots without nixos-hardware on my Pi 4 using those modules, although I haven't yet tried any graphical desktop or audio or anything, so I can't confirm whether that stuff works out of the box. I also want to try whether those modules are actually necessary for booting.

If it does work out of the box, we should change the example config accordingly.

**Willing to help?**
Yes, once I tried out video, audio, 3D acc, etc. on my RPi4 I can document that.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix.dev/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by proofconstruction** [comment]
Just tried - you can indeed now just download the `img` file, write it to the SD card (or USB if the boot-from-USB firmware setting is enabled), boot, and `nixos-generate-config` + `nixos-rebuild` without needing to add anything from `nixos-hardware`.
