### ISSUE TITLE
Referencing the channel:* syntax

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nix.dev#60]
Hi,

I recently learned about the `channel:*` syntax to reference a channel without the need to specify a full URL. I used it like this

```
$ nix-build -I nixpkgs=channel:nixos-unstable '<nixpkgs>' -A calibre
```

to check if `calibre` builds in the `nixos-unstable` channel.

The [Pinning Nixpkgs](https://nix.dev/reference/pinning-nixpkgs.html) tutorial doesn't mention this syntax. Do you want a PR to add it?

**Comment by domenkozar** [comment]
Let's put that in reference instead.

**Comment by DamienCassou** [comment]
The section I'm referencing above ([Pinning Nixpkgs](https://nix.dev/reference/pinning-nixpkgs.html)) is indeed part of "Reference". What do you want me to do then?

**Comment by fricklerhandwerk** [comment]
This has been in the linked page for a while now, closing.
