### ISSUE TITLE
Learning Journey tutorial - Trivial builders

### ISSUE THREAD

**Issue by zmitchell** [NixOS/nix.dev#602]
## Project description
Not every project is compiling Chromium. Sometimes you just want to ensure that specific packages are available when you run a shell script. This tutorial will focus on using trivial builders to put together a small package.

## Steps

- [ ] Submit a PR with an outline of the tutorial
- [ ] Submit a PR with a draft of the tutorial

## Ideas
- You could build up a `writeScriptBin` by starting from `writeTextFile` that manually puts the file in `/bin` and makes it executable.
- You could show how running commands with `nix-shell -p` can be "saved" to a package with `writeShellApplication` to make sure that the script is persisted and the dependencies are available.

**Comment by zmitchell** [comment]
The current status of this issue is that we've decided that it may just be better to improve the reference documentation rather than trying to write a tutorial that ties together a handful of trivial builders since, as the name implies, they are "trivial".

**Comment by brianmcgee** [comment]
Took me longer than I hoped but here's my first pass https://github.com/NixOS/nixpkgs/pull/249721
