### ISSUE TITLE
link "suggest edit" on the GitHub icon doesn't work

### ISSUE THREAD

**Issue by rapenne-s** [NixOS/nix.dev#611]
**Observations**

a github link isn't working

**Problem**

On https://nix.dev/tutorials/first-steps/reproducible-scripts if you click on the github logo and click "suggest edit", you land on https://github.com/NixOS/nix.dev/edit/main/source/tutorials/first-steps/reproducible-scripts.md which is a 404

This seems to be the case for all the pages (I only tried a few random)

**Comment by yukiisbored** [comment]
@fricklerhandwerk Sure, please assign me :)
