### ISSUE TITLE
/tutorials/nix-language is dead

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nix.dev#615]
**Observations**
https://nix.dev/tutorials/nix-language is (well, [should be](https://github.com/NixOS/nix.dev/issues/614)) a 404. That URL is linked from https://zero-to-nix.com/concepts/nix-language and potentially other places.

**Problem**

**Approaches**
It should redirect to https://nix.dev/tutorials/first-steps/nix-language, probably

**Willing to help?**
No, sorry

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix.dev/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by yukiisbored** [comment]
This is currently being worked on here: https://github.com/NixOS/nix.dev/pull/608
