### ISSUE TITLE
Issue on page /tutorials/nixos/installing-nixos-on-a-raspberry-pi.html

### ISSUE THREAD

**Issue by FStefanni** [NixOS/nix.dev#642]
Hi,

I am following the tutorial, and I when I run the command `nixos-rebuild boot`, I get the following error:

```
building Nix...
building the system configuration...
error:
       … while calling the 'head' builtin

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:784:11:

          783|         || pred here (elemAt values 1) (head values) then
          784|           head values
             |           ^
          785|         else

       … while evaluating the attribute 'value'

         at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:753:9:

          752|     in warnDeprecation opt //
          753|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          754|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error:
       Failed assertions:
       - You must set the option ‘boot.loader.grub.devices’ or 'boot.loader.grub.mirroredBoots' to make the system bootable.
```

I am using the currently newer image: https://hydra.nixos.org/build/227318255

So it seems that some bootloader options are missing form the example configuration.

Also, an older tutorial was pointing to nixos-hardware/raspberry-pi/4: is this not more required?
This is the older tutorial part pointing to nixos-hardware:
```
imports = [
      "${fetchTarball "https://github.com/NixOS/nixos-hardware/archive/936e4649098d6a5e0762058cb7687be1b2d90550.tar.gz" }/raspberry-pi/4"
];
```

Regards

**Comment by proofconstruction** [comment]
@FStefanni Thanks for raising this issue - I missed adding the full boot config (and a few other things...) in the previous update. It should now be corrected. My apologies!
> Also, an older tutorial was pointing to nixos-hardware/raspberry-pi/4: is this not more required?

The `nixos-hardware` module is no longer *required* for the rpi4, but is necessary if you have specific hardware requirements like the PoE HAT

**Comment by FStefanni** [comment]
Hi,

thank you for the update. Now it worked perfectly.

Regards
