### ISSUE TITLE
Add support for diff highlighting

### ISSUE THREAD

**Issue by proofconstruction** [NixOS/nix.dev#644]
**Observations**
In code tutorials, it is common to start with a bare-bones example and iteratively build upon it to arrive at the final result.

**Problem**
For our documentation, it would be helpful to highlight how a source file has changed, and rendering the diff would make this obvious.

**Approaches**
GitHub supports this already. If you wrap the following in a fenced code block and use the `diff` info string, this:
```
- old line
+ new line
```
renders as this:
```diff
- old line
+ new line
```

GitHub's `prettylights` syntax highlighter is closed-source, but we already use Pygments which fortunately includes a [`DiffLexer`](https://pygments.org/docs/lexers/#pygments.lexers.diff.DiffLexer) we can use. I'm not sure if implementing this will require producing a [custom Pygments style](https://pygments.org/docs/styles/#creating-own-styles), but that shouldn't be too hard.

**Willing to help?**
Yes. If someone else wants to do this before I get around to it, be my guest, but please reply to this thread to indicate this so we avoid duplicating effort.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix.dev/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by fricklerhandwerk** [comment]
@yukiisbored is this something you could help with?

**Comment by yukiisbored** [comment]
@fricklerhandwerk Sure, assigned myself.
