### ISSUE TITLE
Why not recommend `nix eval` instead of `nix-instantiate --eval`

### ISSUE THREAD

**Issue by strangemonad** [NixOS/nix.dev#673]
**Observations**
https://nix.dev/tutorials/first-steps/nix-language#evaluating-nix-files

Given that the suggested installer recommends turning on the latest flakes flags, why not suggest using the more intuitive `nix eval` command instead of introducing the concept of `nix-instantiate` so early in the tutorials (a new user is just learning about the basics of the nix language at this point).

**Comment by fricklerhandwerk** [comment]
> Given that the suggested installer recommends turning on the latest flakes flags

That would surprise me. Where on nix.dev is that the case?

**Comment by willbush** [comment]
Think this should be closed. `nix eval` is part of the [nix-command](https://nix.dev/manual/nix/2.23/contributing/experimental-features#xp-feature-nix-command) experimental feature. I'm sure there will be a tracking issue to update docs once experimental features are stable.
