### ISSUE TITLE
Debugging Nix expressions

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix.dev#68]
What to do when things go wrong?

- benchmarking
- "my build failed now what?"
- I get a weird error

https://github.com/NixOS/nixpkgs/issues/62913

**Comment by domenkozar** [comment]
https://github.com/NixOS/nix/issues/2665#issuecomment-907584465

**Comment by fricklerhandwerk** [comment]
Superceded by https://github.com/NixOS/nix.dev/issues/774
