### ISSUE TITLE
Update `CODEOWNERS`

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nix.dev#683]
This issue proposes to go through the [`CODEOWNERS`](https://github.com/NixOS/nix.dev/blob/master/.github/CODEOWNERS) file to bring it up to date with the current state of responsibilities.

The main reason to do this is to have clarity around who is responsible for what. The current semantics of the file for this repo is that code owners are automatically added as reviewers to a PR, but anyone with write access can merge.

For an attempt at addressing this, see https://github.com/NixOS/nix.dev/pull/680

**Comment by proofconstruction** [comment]
We decided in the meeting today to just [add the whole team to CODEOWNERS](https://github.com/NixOS/nix.dev/pull/680/commits/b767ac2d8bc86c4804f22957d32fbcd5df3a8e1a), with the Learning Journey stuff set to only ping that team:

```
* @NixOS/documentation-team

# Learning Journey
maintainers/working_groups/learning_journey/ @NixOS/learning-journey-working-group @NixOS/documentation-team
source/tutorials/learning_journey/ @NixOS/learning-journey-working-group @NixOS/documentation-team
```

Can we close this?

**Comment by asymmetric** [comment]
Thanks for taking care of it!
