### ISSUE TITLE
Remove gitpod

### ISSUE THREAD

**Issue by proofconstruction** [NixOS/nix.dev#691]
The README contains a button
![gitpod](https://github.com/NixOS/nix.dev/assets/74747193/36e92d35-1d23-4139-b263-1c8c8158baf2)
 to open the repo for editing in [gitpod](https://gitpod.io), and the repo contains [two](https://github.com/NixOS/nix.dev/blob/master/.gitpod.dockerfile) [files](https://github.com/NixOS/nix.dev/blob/master/.gitpod.yml) for facilitating development there.

To my knowledge, none of the current maintainers are using this, and it's unlikely that drive-by contributors will either.

**Comment by fricklerhandwerk** [comment]
Makes sense to me. @domenkozar objections? Did we overlook anything?

**Comment by domenkozar** [comment]
sgtm
