### ISSUE TITLE
Set `CLOUDFLARE_PROJECT_NAME` repository variable

### ISSUE THREAD

**Issue by yukiisbored** [NixOS/nix.dev#706]
**Observations**

Deploy preview workflow failed.

https://github.com/NixOS/nix.dev/actions/runs/6075318380/job/16481247735

**Problem**

`CLOUDFLARE_PROJECT_NAME` repository variable is not set

**Approaches**

- Set `CLOUDFLARE_PROJECT_NAME` repository variable to `nix-dot-dev`

**Willing to help?**

I don't have access to repository variables, so I couldn't do this.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix.dev/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by fricklerhandwerk** [comment]
@zimbatm if you don't find time, is there anyone else with permissions we could ask?
