### ISSUE TITLE
Issue on page /tutorials/first-steps/declarative-shell.html

### ISSUE THREAD

**Issue by io12** [NixOS/nix.dev#770]
This section says to install `nodejs` for Python 3 support.
> Suppose we a development environment in which Python 3 was installed. The simplest possible way to accomplish this is via the `nix-shell -p` command:
> 
> ```
> $ nix-shell -p git neovim nodejs
> ```

**Comment by fricklerhandwerk** [comment]
Fixed by #793 and #795

@io12 Thanks for reporting!
