### ISSUE TITLE
Copyright date incorrect

### ISSUE THREAD

**Issue by boseiju** [NixOS/nix.dev#796]
Hey,

The following string is currently displayed in the footer on every page:

> © Copyright 2016-1980, NixOS Foundation.

The source looks like it should provide an accurate date:

https://github.com/NixOS/nix.dev/blob/ea8357b14943a67749344c319eedf8bf8f6d3c35/source/conf.py#L18

https://github.com/NixOS/nix.dev/blob/ea8357b14943a67749344c319eedf8bf8f6d3c35/source/conf.py#L82

Is this perhaps an infrastructure issue causing the date to be set inaccurately?

**Comment by yukiisbored** [comment]
@boseiju I believe this is one of the things the Nix build environment does to keep things pure. I think we should just hardcode it and have someone update the copyright year as an annual task.

**Comment by rjpcasalino** [comment]
see: https://github.com/sphinx-doc/sphinx/issues/3451
I've opened a PR https://github.com/NixOS/nix.dev/pull/800

**Comment by rjpcasalino** [comment]
We should be able to close this now with #800 being merged.
