### ISSUE TITLE
Feedback on reproducible shells

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix.dev#80]
Why might it be useful to run the bash hook every time I run the shell (I imagine it can be used as part of git workflows etc, but mentioning a 'real world' example to supplement the 'hello' demonstration would help clarify this I think
    
Why is the direnv command useful - I imagine developers would not need to modify their project shell.nix file that often and would probably restart the shell at least daily when they begin working on a project anyway? Or is that not a common workflow and therefore it's worth installing direnv globally on all dev machines to avoid having to restart the shell?

**Comment by fricklerhandwerk** [comment]
I think this is addressed in the current versions of the respective articles.
