### ISSUE TITLE
Issue on page /tutorials/file-sets.html

### ISSUE THREAD

**Issue by ocharles** [NixOS/nix.dev#826]
This page says

> When using the [flakes and nix-command experimental features](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake), a local directory within a Flake is always copied into the Nix store completely unless it is a Git repository!

But I don't really understand the implications of this warning. Does it mean that filesets are useless when using Nix flakes/`nix develop`? Does it mean the examples on this page don't really work?

**Comment by fricklerhandwerk** [comment]
This note says that if the directory your `flake.nix` is in is *not a Git repository*, evaluating `${./.}` will copy all the files under `./.` into the store. If you have a large directory, this is quite wasteful. This means that `fileset` is particularly useful in that case. https://github.com/NixOS/nix/pull/6530 is supposed to alleviate that limitation when enforcing pure evaluation, but we don't know when it will be completed.

The other note on flakes and `gitTracked` is where `fileset` indeed does not add much benefit: *only* files tracked by Git are copied to the store when the `flakes` experimental feature is enabled, so there is no point filtering for them with `fileset`.

**Comment by fricklerhandwerk** [comment]
> I will still end up copying the entire Git repository into the store before anything happens

With flakes indeed you'll copy the repo into the store, but then filesets will let you extract small store objects for compilation. Which means that if those don't change, you don't have to copy around large chunks during builds.

**Comment by ocharles** [comment]
Got it, thanks!
