### ISSUE TITLE
Put a page at /manual/nix

### ISSUE THREAD

**Issue by lf-** [NixOS/nix.dev#843]
**Observations**

Currently there is a nix manual at https://nix.dev/manual/nix/2.13/language/operators

I tried changing versions by deleting the suffix up to /manual/nix and there was no page there.

**Problem**

Given a URL it should be possible to logically go down the hierarchy to get a version list or similar page. 

**Approaches**

Putting a page there, but I'm not sure what page should be there or by what means it should be put there (and how it interacts with the side site navigation). 

**Willing to help?**

yeah

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix.dev/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by asymmetric** [comment]
I guess it should redirect to /manual/nix/stable/, which we can tackle easily after #830 lands.

**Comment by lf-** [comment]
> I guess it should redirect to /manual/nix/stable/, which we can tackle easily after #830 lands.

Definitely not, it must let you pick version.

**Comment by asymmetric** [comment]
I would go a bit easy on "definitely" and "must" :wink: -- but anyway, I actually agree with you, then I guess it could be a redirect to https://nix.dev/reference/nix-manual, which is the page that lets you pick a version.
