### ISSUE TITLE
Consider explaining "searching for packages"  more detailed

### ISSUE THREAD

**Issue by manuliner** [NixOS/nix.dev#853]
**Observations**
I am doing the nixOS tutorial. A very important part of creating nix.files is the search for missing dependecies. It is just mentioned in a small note that this is the solution for the problem in the tutorial. 

**Problem**

Left out how to find X11/Xlib.h throuhg nix-locate etc.

**Approaches**
Small Tutorial  for a better understanding how to find this dependcies with nix-tools would be nice

**Comment by fricklerhandwerk** [comment]
fixed by https://github.com/NixOS/nix.dev/pull/887
