### ISSUE TITLE
Link does not go where expected

### ISSUE THREAD

**Issue by bew** [NixOS/nix.dev#937]
On the page:
https://nix.dev/tutorials/packaging-existing-software

The [What do you need](https://nix.dev/tutorials/packaging-existing-software#what-do-you-need) section links to:
https://nix.dev/tutorials/nix-language#reading-nix-language
With a fragment pointing to a specific section, but that section don't seem to exist (anymore?)

What was the intended target section?

**Comment by olafklingt** [comment]
It goes where expected, to the head of the nix-language tutorial:
https://github.com/NixOS/nix.dev/blob/dc753f74cd4346f6dfa723cba337e83e8337a071/source/tutorials/nix-language.md?plain=1#L1

**Comment by bew** [comment]
Huh, what's the point of targeting a fragment if it's not a specific section but the entire page?

We could simplify the link to https://nix.dev/tutorials/nix-language (no fragment, clearer)
