### ISSUE TITLE
use an open service on /tutorials/module-system/module-system.html

### ISSUE THREAD

**Issue by autra** [NixOS/nix.dev#953]
Hi!

The current tutorial "Module system Deep Dive" uses the google api, which needs an account and more importantly to give a credit card to google. Not everybody can or want to do that. 

I propose to change this to one of the osm public image server. If you guys are ok with that, I can:

1. ask osm admins for permissions
2. make the changes in the tutorial

Thanks for the awesome website anyway!

**Comment by infinisil** [comment]
I'd love that! The only tricky bit is to make sure that more or less the same concepts are shown.

**Comment by autra** [comment]
Yes, it's a bit of work, also to keep the same coherence and fun factor (with the maps).

Btw, unless I'm mistaken, the part about [Conditional definition](https://nix.dev/tutorials/module-system/module-system#conditional-definitions) does not work (and probably never has?). Nix complains about a missing definition even with the test, and the original video immediately shows a default value for zoom ... So I'm probably gonna remove that part unless someone jumps in and correct me :-)

**Comment by infinisil** [comment]
Ah it's just a missing
```nix
default = null;
```

Should work with that!

**Comment by infinisil** [comment]
Hey @autra, check out this alternate proposal by @djacu: #966

**Comment by autra** [comment]
> Hey @autra, check out this alternate proposal by @djacu: #966

seems way more complete that what I have started 😅 Will comment there (and probably close this one later)

**Comment by autra** [comment]
closing this, as I think #966 is much more advanced.
