### ISSUE TITLE
Windows WSL2 doesn't support --daemon

### ISSUE THREAD

**Issue by ChrisJefferson** [NixOS/nix.dev#98]
On https://nix.dev/tutorials/install-nix.html

WSL2 (the latest version of WSL on Windows) doesn't have systemd, so I need to pass --no-daemon . I don't have a WSL install to test if that supports --daemon I'm afraid.

Seeing as WSL is intended (I think) as a single-user distro mostly anyway (each windows user gets their own linux installation), I don't think this will be a major problem.

**Comment by ChrisJefferson** [comment]
While there, maybe change the nix-shell instruction to:

Check that the installation was successful by opening a **new terminal** and typing:

**Comment by WSLUser** [comment]
You can get your daemon by enabling the systemd hack as found here: https://github.com/shayne/wsl2-hacks

**Comment by ChrisJefferson** [comment]
This has long since been fixed, just having a cleanup of my old issues :)
