### ISSUE TITLE
Documentation for nix.conf

### ISSUE THREAD

**Issue by greg-freewave** [NixOS/nix.dev#990]
https://nixos.org/manual/nix/stable/command-ref/conf-file.html

The above link appears in many places around the internet when searching for information regarding things like customizing the nix shell prompt and how to enable experimental features. 

It appears there is no documentation for nix.conf anymore. Is there somewhere else folks should be looking? Does the information need to be brought over to the new book? I'm not sure whether this is a bug or not but I can't find the documentation anymore.

Thanks!

**Comment by proofconstruction** [comment]
There were a series of deployment issues after a regression was introduced, but this should now be resolved. Please check and confirm. For more information: https://github.com/NixOS/nixos-homepage/issues/1452
