### ISSUE TITLE
404. Nixos.org link to channels in "learning" 

### ISSUE THREAD

**Issue by hugosenari** [NixOS/nix.dev#996]
Nixos.org link to "[What is a channel?](https://nixos.org/manual/nix/stable/package-management/channels.html)" in "[learning](https://nixos.org/learn/)" leads to 404 page.

**Comment by hugosenari** [comment]
@fricklerhandwerk  Sadly it didn't fixed [Nix expression language](https://nixos.org/manual/nix/stable/expressions/expression-language.html) in https://nixos.org/learn/

**Comment by fricklerhandwerk** [comment]
Will look into it

**Comment by fricklerhandwerk** [comment]
Seems fixed now.
